allowCompoundWords: true
dictionaries:
  - cpp
  - cpp-compound-words
  - cpp-legacy
  - en_US
  - en-gb
  - fullstack
  - git
  - markdown
  - misc
  - npm
  - rust
  - rust-crates
  - shellscript
  - softwareTerms
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - Cargo.lock
  - target/**
ignoreRegExpList:
  - kuroné?
  # cspell:disable-next-line
  - '[\uff00-\uffef]+'
language: en,ja
useGitignore: true
version: '0.2'
words:
  - aichat
  - clau
  - claudex
  - clauder
  - decckm
  - embark
  - greppable
  - hsomething
  - kito
  - jvim
  - kyuukyuu
  - lossily
  - ollama
  - qjunk
  - qorrection
  - qwen
  - rexpect
  - swatinem
  - toctou
  - xclaude
